{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.roleName" . }}
  namespace: {{ include "app.namespace" . }}
rules:
  # Define your rules here
  {{- range .Values.role.podPermissions }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: {{ .verbs | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
